# 基本信息
title: shino
description: 'shino.space - shino 的个人网站'
url: 'https://shino.space'
baseurl: '/'

# 联系方式
author:
  name: 'shino'
  email: shino@shino.space
  # twitter_username: shino_996
  github_username: shino-996
  # qq: 852217956
google_analytics: 'UA-78168136-1'

# 背景图
pixiv:
  image_id: 68126514
  name: 無題
  author_id: 9790122
  author: smile

# liquid模板
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# 文件路径
destination: ./_site
permalink: /:year/:title/
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - newpost.sh
  - LICENSE

# markdown相关
markdown: kramdown
excerpt_separator: <!-- more -->

kramdown:
  input: kramdown
  syntax_hghlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
      line_format: '%2i'

# 插件
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed]

# jekyll-paginate设置
paginate: 10
paginate_path: /page:num
